core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe.urls')),
     path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/urls.py
from django.urls import path
from .views import home, detail, CategoryView

urlpatterns = [
    path('', home, name='home'),
    path('<int:pk>/', detail, name='detail'),
    path('recipe/<slug:category>/', CategoryView.as_view(), name='recipe_by_category'),
]

recipe/models.py
from django.db import models
from django.contrib.auth.models import User
from django_ckeditor_5.fields import CKEditor5Field



LEVEL_CHOICES = (
    ('F', 'Facile'),
    ('M', 'Moyenne'),
    ('D', 'Difficile'),
)

class Recipe(models.Model):

    CATEGORIE_CHOICES = (
        ('ACCO', 'Accompagnement'),
        ('PLAT', 'PLat'),
        ('DESS', 'Dessert'),
        ('BOIS', 'Boisson'),
    )


    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250)
    category = models.CharField(max_length=4, choices=CATEGORIE_CHOICES)
    description = CKEditor5Field('Description', config_name='extends')
    recipe_img = models.ImageField(upload_to='Image/')
    ingredient = CKEditor5Field('Ingredient', config_name='extends')
    instruction = CKEditor5Field('Instruction', config_name='extends')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    time_cook = models.CharField(max_length=10)
    temps_cuisson = models.CharField(max_length=10)
    num_people = models.CharField(max_length=10)
    level = models.CharField(max_length=2, choices=LEVEL_CHOICES)
    rate = models.IntegerField()
 

    class Meta:
        ordering = ['-created']
       
    def __str__(self):
        return self.title


class Comment(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=50)
    email = models.EmailField()
    commentaire = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'
    

recipe/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['name', 'email', 'commentaire']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control text-input'}),
            'email': forms.EmailInput(attrs={'class': 'form-control text-input'}),
            'commentaire': forms.Textarea(attrs={'class': 'form-control text-area', 'row': 4})
        } 
        labels = {
            'name': 'NOM',
            'email': 'E-MAIL',
            'commentaire': 'COMMENTAIRE'
        }
    

recipe/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from .forms import CommentForm
from django.views.decorators.http import require_POST
from .models import Recipe

def home(request):
    recipes = Recipe.objects.all()
    return render(request, 'recette/home.html', locals())


def detail(request, pk):
    recipe = get_object_or_404(Recipe, id=pk)
    category_name = recipe.get_category_display()
    current_category = recipe.category
    comments = recipe.comments.filter(active=True)
    comment = None
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.recipe = recipe
            comment.save()
    else:
        form = CommentForm()
    similar_recipes = Recipe.objects.filter(category=current_category).exclude(id=recipe.id)
    context = {
        'recipe': recipe,
        'similar_recipes': similar_recipes,
        'category_name': category_name,
        'form': form,
        'comments': comments,
    }
    return render(request, 'recette/detail.html', context)


class CategoryView(View):
    def get(self, request, category):
        recipes = Recipe.objects.filter(category=category)
        categorie_choices = Recipe.CATEGORIE_CHOICES
        return render(request, 'recette/category.html', locals())

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>Recettes Ivoirienne</title>
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.css"
      integrity="sha512-6lLUdeQ5uheMFbWm3CP271l14RsX1xtx+J5x2yeIDkkiBpeVTNhTqijME7GgRKKi6hCqovwCoBTlRBEC20M8Mg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
      integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <!-- Google icons -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"
    />
  </head>
  <body>
    <header>
      <div class="container-fluid p-1 bg-light">
        <i class="bx bxl-facebook-circle text-primary"></i>
        <i class="bx bxl-instagram"></i>
      </div>
    </header>
    <section class="header" id="header">
      <div class="container-fluid p-0 text-center">
        <div class="row">
          <img src="{% static 'img/amoirie.png' %}" alt="" />
          <div class="header-text text-center text-uppercase mt-4">
            <h1 class="title">Recettes Ivoiriennes</h1>
            <h4 class="subtitle text-center mb-3">Vibes Ivoiriens</h4>
            <small class="small-title"
              >Cuisinez, mangez, buvez et partagez</small
            >
          </div>
        </div>
        <hr />
        <div class="nav container-fluid p-0">
          <div
            class="container d-flex justify-content-center align-items-center"
          >
            <div class="text-center">
              <a href="{% url 'home' %}" class="nav-link active">Accueil</a>
              <a class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Recettes
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li>
                    <a
                      class="dropdown-item"
                      href="{% url 'recipe_by_category' 'ACCO' %}"
                      >ACCOMPAGNEMENT</a
                    >
                  </li>
                  <li>
                    <a
                      class="dropdown-item"
                      href="{% url 'recipe_by_category' 'PLAT' %}"
                      >PLAT</a
                    >
                  </li>
                  <li>
                    <a
                      class="dropdown-item"
                      href="{% url 'recipe_by_category' 'DESS' %}"
                      >DESSERT</a
                    >
                  </li>
                  <li>
                    <a
                      class="dropdown-item"
                      href="{% url 'recipe_by_category' 'BOIS' %}"
                      >BOISSON</a
                    >
                  </li>
                </ul>
              </a>
              <a href="/" class="nav-link">Astuces</a>
            </div>
            <div class="search-box">
              <input type="search" name="q" id="search" class="search" />
              <i class="bx bx-search-alt" id="search-icon"></i>
            </div>
          </div>
        </div>
        <hr />
      </div>
    </section>

    {% block content %} {% endblock %}
    <!-- footer -->
    {% include "includes/footer.html" %}
    <!-- -->
    {% block scripts %} {% endblock scripts %}

    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"
      integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <script>
      $(".slider").slick({
        dots: true,
        infinite: true,
        speed: 300,
        slidesToShow: 3,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 2000,
        responsive: [
          {
            breakpoint: 1024,
            settings: {
              slidesToShow: 3,
              slidesToScroll: 3,
              infinite: true,
              dots: true,
              arraws: false,
            },
          },
          {
            breakpoint: 600,
            settings: {
              slidesToShow: 2,
              slidesToScroll: 2,
              arrows: false,
            },
          },
          {
            breakpoint: 480,
            settings: {
              slidesToShow: 1,
              slidesToScroll: 1,
              arrows: false,
            },
          },
          // You can unslick at a given breakpoint now by adding:
          // settings: "unslick"
          // instead of a settings object
        ],
      });
    </script>
  </body>
</html>

templates/includes/footer.html
<hr />
<div class="container text-center text-uppercase py-3">
  &copy; 2023 Designer By Mustafa | Inspired by Recettes Africa
</div>

templates/recette/category.html
{% extends "base.html" %}
<!-- -->
{% load l10n %}
<!-- load static -->

{% load static %}
<!-- block content -->
{% block content %}
<div class="container category">
  <h4>Categories:</h4>
  <div class="row">
    {% for recipe in recipes %}

    <div class="col-lg-4 cat-card">
      <img src="{{ recipe.recipe_img.url }}" alt="" />
      <div class="cat-content">
        <h4 class="text-center cat-title py-4">{{ recipe.title }}</h4>
        <span class="cat-meta cat-date"
          >{{ recipe.created|date:'d F Y' }} &#183; by
        </span>
        <span class="cat-meta cat-author ps-1">{{ recipe.author }} </span>
        <span class="cat-meta ps-1">
          &#183; {{ recipe.comments.count }} comments</span
        >
        <p>{{ recipe.description|safe|truncatewords:30 }}</p>
        <div class="link text-center">
          <a
            href="{% url 'detail' recipe.id %}"
            class="btn text-center cat-link"
            >Voir detail</a
          >
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

templates/recette/detail.html
{% extends "base.html" %}

<!-- -->
{% load l10n %}
<!-- load static -->
{% load static %}

<!-- block content -->
{% block content %}

<div class="inner-wrapper container">
  <main class="site-main" id="main">
    <div class="row">
      <div class="content-area col-12 col-md-12 col-lg-8 p-5">
        <div class="post-thumb mb-3">
          <img src="{{ recipe.recipe_img.url }}" alt="" />
        </div>
        <header class="entry-header text-center">
          <h1 class="entry-title text-center">{{ recipe.title }}</h1>
          <div class="entry-meta">
            <span class="entry-author"
              >Written by <span>{{ recipe.author }} </span></span
            >
            <span class="entry-date"
              >&middot; on {{ recipe.created|date:'d F Y' }}
            </span>
            <span class="entry-category"
              >&middot; in <span>{{ category_name }}</span></span
            >
          </div>
        </header>
        <div class="entry-content">
          {{ recipe.description|safe }}
          <div class="entry-detail">
            <h3 class="title detail-title">Details</h3>
            <div class="detail-content">
              <div class="detail detail-pers">
                <div class="detail-header">
                  <i class="bx bx-user icon"></i>
                  <span>Personne</span>
                </div>
                {{ recipe.num_people }}
              </div>
              <div class="detail detail-prep">
                <div class="detail-header">
                  <i class="bx bxs-bowl-hot icon"></i>
                  <span>Temps de preparation</span>
                </div>
                {{ recipe.time_cook }}
              </div>
              <div class="detail detail-cuis">
                <div class="detail-header">
                  <span class="material-symbols-outlined icon"> cooking </span>
                  <span>Temps de cuisson</span>
                </div>
                {{ recipe.temps_cuisson }}
              </div>
              <div class="detail detail-level">
                <div class="detail-header">
                  <span class="material-symbols-outlined icon">
                    electric_bolt
                  </span>
                  <span>Difficulté</span>
                </div>
                {{ recipe.get_level_display }}
              </div>
            </div>
          </div>
          <div class="entry-ingredient">
            <h3 class="title ingredient-title">Ingredients</h3>
            <div class="ingredient-content">{{ recipe.ingredient|safe }}</div>
          </div>
          <div class="entry-desc">
            <h3 class="title description-title">Direction</h3>
            <p>{{ recipe.instruction|safe }}</p>
          </div>

          <div class="related-recipe mt-3">
            <h3>Related posts:</h3>
            <div class="similar-items text-center py-4 px-2">
              <div class="row">
                {% for recipe in similar_recipes %}

                <div class="col-6 col-md-6 col-lg-6 px-4 related-recipe">
                  <a href="{% url 'detail' recipe.id %}">
                    <img
                      src="{{ recipe.recipe_img.url }}"
                      alt=""
                      class="img_sr"
                      style="height: 168px"
                    />
                    <h5 class="mt-2">{{ recipe.title }}</h5>
                  </a>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
          <hr />

          {% for comment in comments %}
          <div class="comment mb-3 px-4">
            <div class="comment-user me-3 col-2 text-center">
              <i class="bx bxs-user-circle"></i>
            </div>
            <div class="comment-content ms-3">
              <span class="comment-name fs-5 fw-bold">{{ comment.name }} </span>
              <span class="comment-date"
                >on {{ comment.created|date:'d F Y' }}</span
              >
              <p class="comment-body">{{ comment.commentaire }}</p>
            </div>
          </div>
          {% endfor %}
          <h2 class="text-uppercase mb-3 fw-5 mt-5">Laisser un commentaire</h2>
          <small class="sm-d"
            >Votre address e-mail ne sera pas publié, les champ obligatoire sont
            indiqué avec *
          </small>
          <form method="post" class="mt-4">
            {% csrf_token %}
            <!--  -->
            {{ form.as_p }}
            <!--  -->
            <input
              type="submit"
              class="p-3 submit"
              value="LAISSER COMMENTAIRE"
            />
          </form>
        </div>
      </div>
      <div class="sidebar col-12 col-md-12 col-lg-4"></div>
    </div>
  </main>
</div>

{% endblock content %}
<!-- end content -->

{% block scripts %} {% endblock scripts %}

templates/recette/home.html
{% extends "base.html" %}
<!-- Load static -->
{% load static %}
<!-- block content -->

{% block content %}

<section class="home" id="home">
  <div class="container">
    <div class="row slider">
      <div class="col-12 col-md-12">
        <div class="slider-slick">
          <img src="{% static 'img/goyave.png' %}" alt="" />
        </div>
      </div>

      <div class="col-12 col-md-12">
        <div class="slider-slick">
          <img src="{% static 'img/ivoire.png' %}" alt="" />
        </div>
      </div>

      <div class="col-md-12">
        <div class="slider-slick">
          <img src="{% static 'img/slider.png' %}" alt="" />
        </div>
      </div>

      <div class="col-12 col-md-12 text-center">
        <div class="slider-slick text-center">
          <img src="{% static 'img/slider.png' %}" alt="" />
        </div>
      </div>

      <div class="col-12 col-md-12">
        <div class="slider-slick">
          <img src="{% static 'img/goyave.png' %}" alt="" />
        </div>
      </div>

      <div class="col-12 col-md-12">
        <div class="slider-slick">
          <img src="{% static 'img/slider.png' %}" alt="" />
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="grid-items">
        {% for recipe in recipes %}
        <div class="item">
          <div class="item-img">
            <a href="{% url 'detail' recipe.id %}">
              <img src="{{ recipe.recipe_img.url }}" alt="" />
            </a>
          </div>
          <div class="item-content">
            <div class="title-link">
              <a href="{% url 'detail' recipe.id %}">{{ recipe.title }}</a>
            </div>
            <div class="desc-link">
              {{ recipe.description|safe|truncatewords:20}}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>

{% endblock content %}